### ISSUE TITLE
 Improper placement of images on scrolling the tableview #120 

### ISSUE THREAD

**Issue by harshcs** [jquave/Swift-Tutorial#12]
While scrolling the tableview when images are getting downloaded, images are getting placed improperly.
![img_1737](https://cloud.githubusercontent.com/assets/1318176/4988638/195a9220-698f-11e4-9ce1-7aeab4323726.png)

**Comment by jquave** [comment]
How is this an issue with the tutorial? This looks like a completely different app.

**Comment by harshcs** [comment]
This is my app in which I have integrated your code of downloading the image.

```
    var profilePicButton = cell.contentView.viewWithTag(16) as UIButton!
    //profilePicButton!.hnk_setImageFromURL(URL)

    var image = self.imageCache[tempDic["userimage"] as String]


    if( image == nil ) {
        // If the image does not exist, we need to download it
        var imgURL: NSURL = NSURL(string: tempDic["userimage"] as String)!

        // Download an NSData representation of the image at the URL
        let request: NSURLRequest = NSURLRequest(URL: imgURL)
        NSURLConnection.sendAsynchronousRequest(request, queue: NSOperationQueue.mainQueue(), completionHandler: {(response: NSURLResponse!,data: NSData!,error: NSError!) -> Void in
            if error == nil {
                image = UIImage(data: data)

                // Store the image in to our cache
                self.imageCache[tempDic["userimage"] as String] = image
                dispatch_async(dispatch_get_main_queue(), {
                    if let cellToUpdate = tableView.cellForRowAtIndexPath(indexPath) {
                        profilePicButton.setImage(image, forState:UIControlState(0))
                    }
                })
            }
            else {
                println("Error: \(error.localizedDescription)")
            }
        })

    }
    else {
        dispatch_async(dispatch_get_main_queue(), {
            if let cellToUpdate = tableView.cellForRowAtIndexPath(indexPath) {
                profilePicButton.setImage(image, forState:UIControlState(0))
            }
        })
    }
```

Let me know please where I made a mistake.

**Comment by jquave** [comment]
This just isn't related to the tutorial. If you're having a layout issue I would recommend reviewing your auto layout to see what the issue is.

**Comment by harshcs** [comment]
No its not an auto layout issue as you can see that I have used the same code which you have used in your sample app. I am sure when you will download the images with bigger size you will see this issue. Since you are downloading images of very small size so they are getting downloaded immediately so you are not able to see this issue but in actual "this is not reliable code for downloading the images".
My point is where your code is mapping the position of the image where it should get placed after downloading. Let me know if I am wrong and how can I correct this issue.

**Comment by jquave** [comment]
These issues are outside the scope of the tutorial. Your using the viewWithTag function to locate a custom view for the image, but you have not specified any auto layout constraints. (And neither does the tutorial, but that is because auto layout is a different topic, and not necessary for the small images used in the tutorial)

**Comment by harshcs** [comment]
@jquave With all due respect, I would like to mention that I have placed the constraints in the storyboard and this issue is not related to UI. Its about the proper placement of the images after downloading. And regarding the scope of the tutorial, how others can use it in their apps if that is not working properly.
There should be some logic to put the images where they are supposed to. Images are getting downloaded in background thread but which code is taking care that image should get placed on their positions?

**Comment by jquave** [comment]
The code to make sure the images goes to their correct position would be auto layout constraints. The content changes, auto layout produces a new layout for the image.

**Comment by jquave** [comment]
You can also do it the old fashioned way and just manually set the frame of the UIImageView after assigning the image.

**Comment by harshcs** [comment]
OK, please let me know how can I make sure that downloaded image will be placed on proper position using Auto Layout?

"You can also do it the old fashioned way and just manually set the frame of the UIImageView after assigning the image. "
I did it already and I think it will work! Thanks anyways!

**Comment by harshcs** [comment]
Well that is also causing the same issue.
Now I am using

```
    var profilePicButton = UIButton()
    profilePicButton.frame = CGRect(x: 13, y: 13, width: 44, height: 44)        
    cell.contentView.addSubview(profilePicButton)
```
