### ISSUE TITLE
Various compilation time issues

### ISSUE THREAD

**Issue by JuanAntelo** [jquave/Swift-Tutorial#16]
Cloned the repo & got these errors

![screen shot 2015-01-12 at 10 30 36 am](https://cloud.githubusercontent.com/assets/3731947/5705276/1b35e51c-9a46-11e4-9841-3ba4fdb6e20f.png)

**Comment by jquave** [comment]
What version of Xcode? This has changed many times, and always comes down to the same thing: unwrap the optional either through optional binding, or implicitly unwrap with the ! operator (which Xcode even suggests doing)

**Comment by JuanAntelo** [comment]
I figured out that I did not bind the View Controller to the table view via the interface builder, hopefully that helps someone else!
